### PR TITLE
Remove sensio/framework-extra-bundle dependency.

### PR DESCRIPTION
**Pull request by czachor**
Remove deprecated `sensio/framework-extra-bundle` dependency.
See issue #113.
Source: https://github.com/sensiolabs/SensioFrameworkExtraBundle

### CODE REVIEW

**Comment by czachor** [comment]
I had to add the package doctrine/annotations ^1.14. Anyway since v2.0, the AnnotationRegistry::registerLoader method is removed and since 1.8 deprecated.
The package symfony/framework-bundle is also required.

**Comment by artgris** [comment]
thx @czachor  :+1:

**Comment by Ishadijcks** [comment]
Awesome thanks!

**Comment by pfpro** [comment]
Thanks! 

After upgrading to the latest release by running "composer up", sensio/framework-extra-bundle was still in my composer.json. I had to run "composer remove sensio/framework-extra-bundle" manually.
Is this the desired bevaviour, or could this be improved?

**Comment by czachor** [comment]
Maybe it is needed by another package? In my case, the package was completely removed. In another project it remained as a dependency I guess for maker "make:crud" command (not sure).

**Comment by pfpro** [comment]
you were right - in my case it was the isGranted annotation, which i replaced now by the symfony 6.2 approach. thanks for the feedback

**Pull request merged**
